### ISSUE TITLE
No UI updated on AX-92U

### ISSUE THREAD

**Issue by acekm** [DanielLavrushin/asuswrt-merlin-xrayui#1]
Hi and huge thanks for your project! As I am waiting for SNB forum approval - I just wanted to share the issue I have similar to other script user:
- UI is not updated even after reboots and amtm reinstall
- no option for manual VPN config
<img width="615" alt="chrome_QKAUsrEiMe" src="https://github.com/user-attachments/assets/ae785d31-4995-4c87-9c0d-75cf6bb755fe" />

would really appreciate code update or details how to fix this!

K

**Comment by DanielLavrushin** [comment]
@acekm thanks for reporting. This is really odd, may I ask you anyhow to provide the following file from your web ui router?
```
/www/require/modules/menuTree.js
```

It seem the structure from router to router might be different. 


>no option for manual VPN config
What do you mean, not sure I understood :)

**Comment by DanielLavrushin** [comment]
btw, no need to reinstall anything or reboot the router

**Comment by acekm** [comment]
If I understood you correctly:
here is the file (gh doesnt allow js files)
[menuTree.zip](https://github.com/user-attachments/files/18331403/menuTree.zip)


also tried reinstall and noticed following during script deletion:
- menuTree.js not found, skipping unmount.


oh
and now my UI is not displayed correctly haha
![image](https://github.com/user-attachments/assets/8db1e288-7ad5-47d5-8b79-ee16939da3ab)

**Comment by SplattyOne** [comment]
Greetings! Thanks for this project :) Let me join the discussion, my ASUS RT-AX88U also did not have an X-RAY menu section until I corrected the menuTree.js file, below is a screenshot of the error and file with corrected position.
<img width="824" alt="screen_console" src="https://github.com/user-attachments/assets/5d2b261c-4097-4dcb-9c8a-2b6512ee7dcd" />
<img width="602" alt="screen_source" src="https://github.com/user-attachments/assets/b4fdcbc8-d919-40bd-82c0-0379fc73f2bf" />
[menuTree.js.txt](https://github.com/user-attachments/files/18331441/menuTree.js.txt)

**Comment by DanielLavrushin** [comment]
@SplattyOne @acekm guys, thanks a lot, this really helps. Going to fix it asap. 
I guess uninstalling the xraytui should roll back the broken changes.

**Comment by acekm** [comment]
huge thanks, no critical staff - uninstall and reboot returned UI back
sorry, I am a huge noob here, but I am amazed by your work and support!

thanks!

**Comment by DanielLavrushin** [comment]
@acekm @SplattyOne I think this been fixed in [v0.6](https://github.com/DanielLavrushin/asuswrt-merlin-xrayui/releases/tag/v0.6)
can you try to reinstall it? 

remember, you dont need to reboot or reinstall anything else, the changes should reapply after logoff/login into the web interface.

**Comment by acekm** [comment]
> @acekm @SplattyOne I think this been fixed in [v0.6](https://github.com/DanielLavrushin/asuswrt-merlin-xrayui/releases/tag/v0.6) can you try to reinstall it?
> 
> remember, you dont need to reboot or reinstall anything else, the changes should reapply after logoff/login into the web interface.

checked - UI works and present
tried config setup - worked. cannot check xray connection though - see below

some errors found:
1) reboot removed UI menu. run scipt again = success. probably a feature :)
2) route settings via UI - not working. button "add" doesn't do anything
added route via config - this added rules to the UI, but add/delete/edit still don't work - config stays the same
![image](https://github.com/user-attachments/assets/ce8ab804-c21c-4e82-bdf7-2cc92f0ca158)

**Comment by acekm** [comment]
> > @acekm @SplattyOne I think this been fixed in [v0.6](https://github.com/DanielLavrushin/asuswrt-merlin-xrayui/releases/tag/v0.6) can you try to reinstall it?
> > remember, you dont need to reboot or reinstall anything else, the changes should reapply after logoff/login into the web interface.
> 
> checked - UI works and present tried config setup - worked. cannot check xray connection though - see below
> 
> some errors found:
> 
> 1. reboot removed XRAY UI menu. run scipt again = success. probably a feature :)
> 2. route settings via UI - not working. button "add" doesn't do anything
>    added route via config - this added rules to the UI, but add/delete/edit still don't work - config stays the same
>    ![image](https://private-user-images.githubusercontent.com/98755632/400775956-ce8ab804-c21c-4e82-bdf7-2cc92f0ca158.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYyNjM5MDIsIm5iZiI6MTczNjI2MzYwMiwicGF0aCI6Ii85ODc1NTYzMi80MDA3NzU5NTYtY2U4YWI4MDQtYzIxYy00ZTgyLWJkZjctMmNjOTJmMGNhMTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA3VDE1MjY0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxOWVmYTZkZmExNzQzOThiMDIwYWYwMWQ1NzFjOGM5ZjI2YzM0YjFlZWIyN2E0ZTU3ZjI4OTVjOGQzMDJmNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._vsBQipPHUe7rCF_JRBzB53zWBdaNT1-JWb6G3DLzJQ)

i've tested 0.8 - menu for routing works, rules don't save
1) when clicked apply - deleted rule
2) also reloading with rule added has nuked my config.json file

hope this helps

**Comment by DanielLavrushin** [comment]
@acekm 
that is odd - sorry about nuking it :(

Can you try the new one (v0.9, just run install again).  
I might suspect the browser cache. Just in case try being on the xray page to press f12 to invoke the debuging tools and find the `disable cache` check box 
![image](https://github.com/user-attachments/assets/7809fca7-ceae-4730-9ba1-a2e2e73be0c2)

and then press ctrl+f5 for hard reload.

I just made a dummy rule

![image](https://github.com/user-attachments/assets/b48d621a-2149-42d5-a45b-61e035f6bd4a)

and got it in my config

![image](https://github.com/user-attachments/assets/5c400086-3a9b-4cd3-82bc-cfa232e2217b)

**Comment by DanielLavrushin** [comment]
resolved

**Comment by acekm** [comment]
hi! sorry, I was only able to review updates today
- unfortunately the Routing settings are not saved

what I have noticed
1) if I setup the config based on your WIKI and via UI  - it saves Route, but for some reason I cannot use my XRAY config
2) if I set it up via SSH / nano in config file and just copy my config - it saves it and it connects to my server. but for some reason I cannot test if its working

I will test my config and will try to fidgues whats wrong and I will open a new issue if needed

thanks a lot and good luck!
